name: Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  pull_request:
    branches: 
      - dev
      - '*epic*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  php-unit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2
    services:
      mysql-test:
        image: 'mysql/mysql-server:8.0'
        env:
          MYSQL_DATABASE: ants
          MYSQL_USER: github
          MYSQL_PASSWORD: password
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v3
      - name: Install additional PHP extensions
        run : |
          apt-get update 
          apt-get install -y gnupg gosu curl ca-certificates zip unzip git supervisor sqlite3 libcap2-bin libpng-dev python2 
          mkdir -p ~/.gnupg 
          chmod 600 ~/.gnupg 
          echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf 
          apt-key adv --homedir ~/.gnupg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E5267A6C 
          apt-key adv --homedir ~/.gnupg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C300EE8C 
          echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu impish main" > /etc/apt/sources.list.d/ppa_ondrej_php.list 
          apt-get update 
          php -r "readfile('https://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer 
          apt-get clean 
          rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
          setcap "cap_net_bind_service=+ep" /usr/bin/php8.2
      - name: Install composer dependencies
        run: |
          composer install --no-scripts
      - name: Prepare Application
        run: |
          cp .env.ci .env
          php artisan key:generate
      - name: Run Testsuite
        run: vendor/bin/phpunit tests/
